const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('sk', {
  getState: () => ipcRenderer.invoke('state:get'),
  patch: (p) => ipcRenderer.invoke('settings:patch', p),
  setEnabled: (v) => ipcRenderer.invoke('enabled:set', v),
  readPack: (id) => ipcRenderer.invoke('pack:read', id),
  addPack: (kind) => ipcRenderer.invoke('pack:add', kind),
  removePack: (id) => ipcRenderer.invoke('pack:remove', id),
  openFolder: () => ipcRenderer.invoke('open:folder'),
  openKit: () => ipcRenderer.invoke('open:kit'),
  listPacks: () => ipcRenderer.invoke('packs:list'),
  listAmbience: () => ipcRenderer.invoke('amb:list'),
  readAmbience: (id) => ipcRenderer.invoke('amb:read', id),
  addAmbience: () => ipcRenderer.invoke('amb:add'),
  removeAmbience: (id) => ipcRenderer.invoke('amb:remove', id),
  listMusic: () => ipcRenderer.invoke('music:list'),
  addMusic: () => ipcRenderer.invoke('music:add'),
  removeMusic: (name) => ipcRenderer.invoke('music:remove', name),
  captureHotkey: () => ipcRenderer.invoke('hotkey:capture'),
  dropPacks: (files) => ipcRenderer.invoke('pack:drop', [...files].map((f) => webUtils.getPathForFile(f))),
  onKeyUp: (cb) => ipcRenderer.on('keyup', (_e, code) => cb(code)),
  onScroll: (cb) => ipcRenderer.on('scroll', (_e, dir) => cb(dir)),
  onMouse: (cb) => ipcRenderer.on('mouse', (_e, button, down) => cb(button, down)),
  ignoreMute: () => ipcRenderer.invoke('context:ignore'),
  getContext: () => ipcRenderer.invoke('context:get'),
  onContext: (cb) => ipcRenderer.on('context', (_e, c) => cb(c)),
  themeChrome: (c) => ipcRenderer.invoke('theme:chrome', c),
  getHealth: () => ipcRenderer.invoke('health:get'),
  restartHook: () => ipcRenderer.invoke('hook:restart'),
  onHealth: (cb) => ipcRenderer.on('health', (_e, h) => cb(h)),
  onKey: (cb) => ipcRenderer.on('key', (_e, code, t) => cb(code, t)),
  onEnabled: (cb) => ipcRenderer.on('enabled', (_e, v) => cb(v)),
});
