// Builds renderer/icons.js from Lucide (https://lucide.dev, ISC licence) so the app ships only the icons it uses.
// Add a name to NAMES, run `npm run icons`, then use it as <i class="ic" data-icon="name"></i> or icon('name').
const fs = require('fs');
const path = require('path');

const NAMES = [
  // tabs
  'zap', 'keyboard', 'cloud-rain', 'timer', 'calendar-clock', 'palette', 'settings',
  // actions
  'power', 'trash-2', 'play', 'pause', 'skip-forward', 'shuffle', 'plus', 'folder-open', 'rotate-ccw', 'check',
  'scale', 'sparkles',
  // cards
  'sliders-horizontal', 'clapperboard', 'mouse-pointer-click', 'trophy', 'audio-lines', 'audio-waveform', 'gauge',
  'mouse', 'wind', 'activity', 'music', 'moon', 'bell-off', 'app-window', 'sun', 'monitor', 'headphones', 'folder',
  'heart-pulse', 'info', 'layers', 'droplets', 'clock', 'volume-2', 'keyboard-music', 'palette',
];

const dir = path.join(__dirname, '..', 'node_modules', 'lucide-static', 'icons');
const out = {};
for (const name of [...new Set(NAMES)]) {
  const file = path.join(dir, name + '.svg');
  if (!fs.existsSync(file)) { console.error('No such Lucide icon:', name); process.exitCode = 1; continue; }
  const svg = fs.readFileSync(file, 'utf8');
  out[name] = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>')).replace(/\s+/g, ' ').trim();
}

const body = Object.entries(out).map(([k, v]) => `  '${k}': '${v.replace(/'/g, "\\'")}',`).join('\n');
fs.writeFileSync(path.join(__dirname, '..', 'renderer', 'icons.js'),
`// Generated by tools/build-icons.js from Lucide (ISC licence, https://lucide.dev). Do not edit by hand.
export const ICONS = {
${body}
};
`);
console.log(`wrote ${Object.keys(out).length} icons`);
